bool test_square_positive();
bool test_square_positive_p2_to_p1();
bool test_square_positive_p2_to_negative_p1();
bool test_square_positive_p1_to_negative_p2();
bool test_square_positive_X_negative_Y();
bool test_square_negative_X_positive_Y();
bool test_square_negative();
bool test_square_negative_p2_to_p1();
void true_or_false(bool x);
bool test_lenght_positive();
bool test_lenght_negative();
bool test_lenght_positive_p2_to_p1();
bool test_lenght_positive_p1_to_negative_p2();
bool test_lenght_positive_p2_to_negative_p1();
bool test_lenght_negative_p2_to_p1();
bool test_lenght_positive_X_negative_Y();
bool test_lenght_negative_X_positive_Y();